import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button className="px-4 py-2 font-bold text-white bg-blue-500 rounded hover:bg-blue-900">
        This is a button
      </button>
    </>
  );
};

export default Home;
